### PR TITLE
feat: update Human-GEM svg:s with MA ids

### PR DESCRIPTION
**Pull request by inghylt**
Please build with the new svg files and see that everything is working correctly in the map viewer. The missing reactions seems to have the same numbers as before. From old prints I see that Cytosol had 4803, Golgi apparatus 131, Lysosome 203 and Nucleus 97, which is the case now as well.

If everything looks good, next step will be to update Creative Commons timestamp + Human Gem version and then I'll update to a proper PR

### CODE REVIEW

**Comment by e0** [comment]
I tested several maps, clicking on reactions and metabolites, searching, as well as clicking on the links to 2D maps from the gem browser pages. Apart from the mismatched components we discussed before, everything seems to work great!

**Comment by mihai-sysbio** [comment]
This is deployed on the dev server, and I second @e0's comment above. Will try to look tomorrow via a detailed diff.

**Comment by mihai-sysbio** [comment]
The `triglicerides_formation` map should not be added back via this PR - this subsystem has been removed from Human-GEM.

**Comment by mihai-sysbio** [comment]
Would it make sense to manually remove all the 233 `HMR_` matches that have remained in 13 of the maps? If yes, I can volunteer to do this as part of this PR.

**Comment by inghylt** [comment]
I'm currently working on scripts to get metabolite and reaction ID:s that don't have MA id:s. I would prefer having a record of these before starting to remove anything. But your call if if needs to be done ASAP

**Comment by mihai-sysbio** [comment]
Thanks @inghylt ! Let's stick to the initial plan then - inspect the problem as part of this work, and implement the decision as part of a different issue&PR.

**Review by mihai-sysbio — APPROVED** [review]
Looks great so far! I've had a look through the detailed diff for all the maps and I couldn't spot any issues.

**Comment by mihai-sysbio** [comment]
It looks like `triglycerides_formation.svg` was added back.

**Comment by inghylt** [comment]
Good catch, fixed it with git rebase and have also removed the map in the forked Human-maps PR

**Review by mihai-sysbio — APPROVED** [review]

**Review by e0 — APPROVED** [review]
Great job! I tested some of the edge cases and they all seem to have been replaced correctly.

**Pull request merged**
