### PR TITLE
feat: more models

### PR DESCRIPTION
**Pull request by mihai-sysbio**
This PR contains all the new models added to Met Atlas, with some map listing curation as well.
@nanjiangshu the new annotation files have been added, they have been renamed to contain `-new`.
The `.plain` extension used so that these files will not be stored with Git LFS, but with normal versioning.

To do:
- [ ] remove old annotation files
- [ ] update annotation files for all models (not just Human-GEM)
- [ ] update all models

### CODE REVIEW

**Comment by nanjiangshu** [comment]
Hi @mihai-sysbio, I could not find any new annotation files for all models except Human-GEM at https://github.com/SysBioChalmers. Should be wait for the modellers to generate them or are there any available scripts that can we can generate them from the raw data?

For `yeast-GEM` at https://github.com/SysBioChalmers/yeast-GEM, there is not even a subfolder `model`. Or is this repo the wrong one?

**Comment by mihai-sysbio** [comment]
Yeast-GEM is a bit special, not yet following the same setup as Human-GEM and the rest. Work has started in this direction, but for now it seems easiest to ignore Yeast-GEM.
The annotations for all models except Yeast-GEM will be mostly the same, so for now it is good enough if the same annotation files are used for these models.
@Hao-Chalmers is there any forecast regarding annotations in the new format for all the models derived from Human-GEM?

**Comment by Hao-Chalmers** [comment]
@mihai-sysbio for now the annotation information unique to animal GEMs are also in `tsv` files (e.g. `mouseSpecificMets.tsv`) and deposited in corresponding repos. In the future, these files might be merged together and placed in a centralized repo.

**Comment by mihai-sysbio** [comment]
@Hao-Chalmers, to be more specific, regarding these `tsv` files in the different repos at the moment: 
- the model-specific annotation files do not sit in the `/model` folder, but in the `/data` folder instead.
- the model-specific annotation files do not have the same headers as the original in Human-GEM.

What I meant in the question above
> annotations in the new format for all the models derived from Human-GEM?

was if you have any plans for obtaining annotation files for these models that are identical in path and structure to the ones in Human-GEM?

**Comment by Hao-Chalmers** [comment]
> was if you have any plans for obtaining annotation files for these models that are identical in path and structure to the ones in Human-GEM?

there is no plans for this yet.

**Comment by mihai-sysbio** [comment]
@Hao-Chalmers  Metabolic Atlas will use this new annotation format from Human-GEM as default, so for the annotation to be picked up for the rest of the models equivalent files will be needed.

**Comment by Hao-Chalmers** [comment]
@mihai-sysbio sounds good, let's move toward this direction

**Comment by mihai-sysbio** [comment]
This PR is closed in favour of #8.

**Pull request closed without merging**
