### PR TITLE
feat: add a flag to show all updatable models

### PR DESCRIPTION
**Pull request by nanjiangshu**
This PR is related to one of the acceptance criteria of the issue [#970](https://app.zenhub.com/workspaces/metatlas-sprint-607745622d49260019ce115a/issues/metabolicatlas/metabolicatlas/970)

**Test**
Run the command 
```
./utils/fetch_release_data.py -u
```
And it will output something like below
```
Yeast-GEM can be updated: 8.4.2 => 8.6.0
Human-GEM can be updated: 1.10.0 => 1.11.0
Mouse-GEM can be updated: 1.2.0 => 1.3.0
Rat-GEM can be updated: 1.2.0 => 1.3.0
Zebrafish-GEM can be updated: 1.1.0 => 1.2.0
Fruitfly-GEM can be updated: 1.1.0 => 1.2.0
Worm-GEM can be updated: 1.1.0 => 1.3.0
```

### CODE REVIEW

**Comment by inghylt** [comment]
Updated `requirements.txt` since I could not run the new changes without adding `packaging` as a dependency. `matplotlib==3.0.3` prevented me from using `requirements.txt` properly so had to temporarily delete it to make things work, but I'm not sure if that's local or not yet. Will look into it more next week and create an issue for it if needed

**Review by inghylt — APPROVED** [review]
Very nice! Tried out both the command and the stack as well and everything looks good :+1:

**Review by e0 — APPROVED** [review]
This seems to work really nicely! I had a bit of a problem while installing and running as well but I think I can add those comments to #27.

**Review by MalinAhlberg — APPROVED** [review]
Nice, I think this is script really convenient to have!

**Pull request merged**
