### PR TITLE
Feat: update models

### PR DESCRIPTION
**Pull request by nanjiangshu**
This PR together with https://github.com/MetabolicAtlas/MetabolicAtlas/pull/1145 closes [#1081](https://github.com/MetabolicAtlas/MetabolicAtlas/issues/1081)

**Changes been done**
1. Human-GEM is updated to version 1.12.0
2. Yeast-GEM is updated to version 8.6.2

For Yeast-GEM
1. Some mismatches in the `subsystemSVG.tsv` and the YAML file are fixed manually
2. custom maps that are already included in the model file (v8.6.2) are removed from the file `customSVG.tsv`

Regarding the mismatch of Yeast-GEM version cased by the  patch releases, that is, v8.6.2 is shown in the integrated models panel but v8.6.0 is shown in the history map, it is probably good to add an explanation somewhere. Since there is no such text at any place regarding the history map, I think it is better to address this problem in a new issue. 

Details can be found in [this comment](https://github.com/MetabolicAtlas/MetabolicAtlas/issues/1081#issuecomment-1254236303)

**Additional info**
I've found a problem some weird text shown in the model search result table when viewing on Safari, but not on Firefox nor Chrome. Please verify if it is the case for you as well. For me, the problem exist when building with all `main` branches. 
Screenshot 2022-09-22 at 11 17 09

### CODE REVIEW

**Comment by MalinAhlberg** [comment]
Nice!
It works well as far as I can tell. Regarding the bug when searching for `dd2` in Rat-GEM, I can not reproduce it, but I do not have Safari.
A question: when comparing to https://metabolicatlas.org/gems/repository, many more models seems to have been updated (eg FruitFly from `1.1.0` to `1.2.0`). When was this done?

**Review by inghylt — COMMENTED** [review]
Nice work! It would be nice to get another Mac users input (ping @e0 or @mihai-sysbio) to see if they have the problem with weird text when searching. If so I don't think we should merge this before it is fixed.

And regarding the mismatch of Yeast-GEM version, I think it makes sense to create a new issue for this

**Comment by e0** [comment]
> Mac

I can confirm that this problem shows up in Safari here too. Will try to go through the PR now to see if I can spot anything.

**Comment by e0** [comment]
I looked up this Safari problem a bit now. It seems like a `Vite` related problem that's also reported here: https://github.com/vuejs/vitepress/issues/218

It seems like it's only affecting `development` mode so we should be fine. I can also confirm that if you manually set the encoding (UTF-8 instead of Default), these weird characters will disappear.

image

**Comment by e0** [comment]
> A question: when comparing to https://metabolicatlas.org/gems/repository, many more models seems to have been updated (eg FruitFly from `1.1.0` to `1.2.0`). When was this done?

It seems like most of these were done in [this PR](https://github.com/MetabolicAtlas/data-files/pull/29/files#diff-2f0a23577e037beb4719b09f21dd490235e6afc6b2eb9ee11ff71c349a86bfd0). It was merged at the end of May though so I'm a bit confused why the production site doesn't have these versions since we have deployed to it after that.

**Review by e0 — APPROVED** [review]
Great work @nanjiangshu!

**Comment by nanjiangshu** [comment]
> Nice! It works well as far as I can tell. Regarding the bug when searching for `dd2` in Rat-GEM, I can not reproduce it, but I do not have Safari. A question: when comparing to https://metabolicatlas.org/gems/repository, many more models seems to have been updated (eg FruitFly from `1.1.0` to `1.2.0`). When was this done?

As @e0 pointed out, most of the models are updated in https://github.com/MetabolicAtlas/data-files/pull/29 already in May. I guess the reason why old models are still used on the production server https://metabolicatlas.org/ is that the repo `data-files` were not up-to-date or in a different branch than `main` at the deployment.

**Comment by nanjiangshu** [comment]
Many thanks to @e0 to figure out the problem with weird characters and good to know that it affects (hopefully) only the development mode.

**Review by inghylt — APPROVED** [review]
Nice work!

**Pull request merged**
