### PR TITLE
fix: typos

### PR DESCRIPTION
**Pull request by inghylt**
**Related issue(s) and PR(s)**  
This PR together with closes #1017

**Type of change**  

- [x] Other
 
**List of changes made**  

Fixed typos

**Screenshot of the fix**  

**Testing**  

- Rebuild and make sure `/gems/repository` works as expected

**Further comments**  

**Definition of Done checklist**  
- [x] My code meets the Acceptance Criteria
- [x] My code follows the [NBIS style guidelines](https://github.com/NBISweden/development-guidelines)
- [x] I have performed a self-review of my own code and commented any hard-to-understand areas
- [x] Tests and lint/format validations are passing
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by MalinAhlberg** [comment]
This is a bit unrelated to this PR, but would still be nice: run this file through `prettier` to increase readability.

**Comment by inghylt** [comment]
@MalinAhlberg Nice suggestion, implemented in fc7c1e02ea3e44c90141e6f99634cdd9fe0e1b36

**Review by MalinAhlberg — APPROVED** [review]
Nice!

**Comment by mihai-sysbio** [comment]
> run this file through `prettier` to increase readability.

This increased the size of the uncompressed file by 10%, so the file was in "minified" like this on purpose, especially that it is meant to be edited. Could you please make sure this size increase becomes irrelevant after compression, when served by Nginx?

**Comment by inghylt** [comment]
@mihai-sysbio Nice feedback! I have compared on dev and there seem to be no difference

Using data-files branch `main`
image

Using data-files current branch `feat/fix-typos`
image

**Comment by mihai-sysbio** [comment]
> I have compared on dev and there seem to be no difference

Great, thank you! I trust the work and @MalinAhlberg's review, so I think this can be merged without further approvals.

**Review by nanjiangshu — APPROVED** [review]
Nice work! 

I can confirm that despite the increasing of the size of the json file after reformatting 
```
-rw-rw-r-- 1 nanjiang nanjiang 495K Aug 16 16:30 gemsRepository.json
-rw-rw-r-- 1 nanjiang nanjiang 566K Aug 19 09:30 gemsRepository-new.json
```
The size of the transferred files to the client side is the same, i.e. 495kb (on Firefox). On chrome the size is slightly bigger (507 kb) but still the same in both cases.

So formatting of the original json file increases the readability but will not increase the size of transferring nor the file size on the client side.

**Pull request merged**
