### PR TITLE
fix: use generic font-family

### PR DESCRIPTION
**Pull request by mihai-sysbio**
To fix a potential licensing issue, and to simplify a JPEG conversion issue for the map thumbnails, this PR replaces in all SVG files
> font-family="Arial"

with 

> font-family="sans-serif"

### CODE REVIEW

**Comment by e0** [comment]
On macOS the default sans-serif is Helvetica and on Windows it’s Arial. Helvetica and Arial are pretty much metrically compatible I think. On Linux machines there are different defaults for `sans-serif` but since Arial was never available I assume that whatever was the default hadn’t caused any problems. I’m unsure if only `font-family: Arial` defaults to the default `sans-serif` font though but it would be good if someone on a Linux machine can verify.

Anyhow, in case we notice any problems caused by `sans-serif` being rendered differently in different systems in the future, there is still the option of choosing an free/open font that’s metrically compatible with Arial and packaging it with our project.

**Comment by mihai-sysbio** [comment]
Thanks for the research @e0 ! This places us in a good point to continue if we encounter problem.

**Review by inghylt — APPROVED** [review]

**Review by e0 — APPROVED** [review]
I looked through a few files and didn't notice any problems. Hopefully the other files are fine too.

**Comment by mihai-sysbio** [comment]
I must admit, I have not checked all 177 files either - it is hard to check with `git-lfs` but they were all changed with the same find and replace.

**Pull request merged**
