### PR TITLE
feat: add custom maps for Yeast-GEM

### PR DESCRIPTION
**Pull request by e0**

### CODE REVIEW

**Comment by e0** [comment]
Sounds good! Do you want to leave the following related PRs pending as well?

- https://github.com/MetabolicAtlas/neo4j-data-generation/pull/12
- https://github.com/MetabolicAtlas/MetabolicAtlas/pull/545

From what I have tested there are no side-effects (except an extra warning message in the data generation code) so it should be safe to merge them. But I understand if we want to wait to merge everything at around the same time as well.

**Comment by mihai-sysbio** [comment]
Since the work is done, let's make the cards reflect that - I propose the merging of the other PRs, especially that they are safe to merge.

**Comment by e0** [comment]
> Since the work is done, let's make the cards reflect that - I propose the merging of the other PRs, especially that they are safe to merge.

There are some checklist items in the card and I have checked off all of them except "add the corresponding SVGs in `data-files`". Is there something else we should do to make it more obvious?

**Comment by mihai-sysbio** [comment]
I'm counting on us being pinged by the researcher whose custom map will be published to remind us about it. Together with a draft PR, I consider this an obvious enough reminder so I'm not inclined to create a Jira card.

**Comment by mihai-sysbio** [comment]
By chance, I found a [commit that removed 6 custom maps for Yeast-GEM](https://github.com/MetabolicAtlas/data-files/commit/9c18f451d2e26f458970e83ea52afa087b30f72b), which I think should now be added back. This would also enable us to close this PR.

**Review by inghylt — APPROVED** [review]

**Pull request merged**
